### ISSUE TITLE
Pressure pipe multiple copy civil 3d

### ISSUE THREAD

**Issue by Sinojpullolickal** [mzjensen/Camber#107]
Hi,
Is there an automation way to copy multiple time pressure pipes to an x offset or z offset?
Just to create a conduits of 3 nos 110mm dia parallel and then same config towards a z value down.

Thank you

**Comment by mzjensen** [comment]
Hi @Sinojpullolickal,

I would look at the _PressurePipeRun.ByObject_ node. For example, you could input a list of polylines or alignments (for the horizontal definition) and then a list of surface offsets (for the vertical definition) to create multiple runs. I would try something like that instead of creating a single run and then copying it.

I do not plan to add any additional functionality to Camber for this because I think it can be accomplished with the tools that are already available.
