### ISSUE TITLE
Label.SetRotation does not accept negative angle (bug)

### ISSUE THREAD

**Issue by KirkWM** [mzjensen/Camber#45]
![image](https://user-images.githubusercontent.com/75384301/140402359-40216ced-6c74-4e8f-ab75-7d3a09863b9a.png)

need to add +360 to make positive
![image](https://user-images.githubusercontent.com/75384301/140402441-c5d33973-a9ac-4ae2-9b2b-0bac02167ed6.png)

**Comment by mzjensen** [comment]
I wouldn't say this is a bug because it does work correctly, the value just has to be in the range of [0,360). This is consistent with what you see when setting the rotation of a label using the grips in the UI. It could be changed to accept values in the range from (-180,180], but I don't that would be a solution so much as just a different convention. Then the same argument could be made for "why doesn't the node accept values greater than 180?"

Do you think this could be handled by providing a better description in the node?

**Comment by KirkWM** [comment]
Yeah as soon as I posted it I second guessed that verbiage sorry. Yeah updating the description with 0-360 would be just fine 👍; perhaps even outputting a null value for negative values would also help.
