### ISSUE TITLE
Problem with Camber.Civil.Toolspace

### ISSUE THREAD

**Issue by chuongmep** [mzjensen/Camber#92]
Hi @mzjensen ,
you has remove class Camber.Civil.Toolspace ? 
https://github.com/mzjensen/Camber/blob/a80a665763c3aab8b15832b1f7ddb0255af9d6ad/Camber/Civil/CivilObjects/CivilObject.cs#L22

I don't find any class contain it ?

**Comment by mzjensen** [comment]
Yes, I was initially thinking of creating that namespace for some upcoming features but decided against it for better library organization. I've been doing work in the main branch because no one else has been contributing to this project. I didn't realize you were interested! I can start doing work in separate branches to avoid something like this in the future.

**Comment by chuongmep** [comment]
thanks you , let do it , i need mofify something in project, maybe better.
